### ISSUE TITLE
Trigger login modal by using the login button in the app bar

### ISSUE THREAD

**Issue by kajdehoop** [xrnl/aginun#121] opened 2020-12-05 14:50 UTC
## Problem that this feature solves
Makes it possible to login using existing username and password

## Feature description

Describe a step-by-step use case of your feature. 

1.  Clicking the login button on the app bar opens a modal
2. This modal has a username and password input field, and a login button
3. The login button dispatches the user/login action with the username and password as arguments

**Comment by DenBaas** [comment] 2021-01-13 14:37
I started working on this today and it is a good issue to start :) 

There is a problem I encountered that is a 503 http error I get when trying to log in: "CORS missing allow origin" and I believe this is a server side issue (because of [https://forum.vuejs.org/t/no-access-control-allow-origin-header/36995](this answer) for example). Can you help me with this?

**Comment by SamLubbers** [comment] 2021-01-15 08:42
@DenBaas awesome that you've started working on this issue and sorry you already ran into a problem that blocked you from making progress.

@kajdehoop could you check if there is an issue with the Authentication server that you set up? The login used to work when we merged the code so I assume it's also a problem on the server side.

Bas, until the issue is fixed, you can start creating the login front-end while faking the server response. To do that you can comment out the code inside the `login` action in the user Vuex store `src/store/modules/user.ts` and just call `commit("setToken", true);`

**Closed** 2021-04-27 14:38 UTC
Labels: auth
