### ISSUE TITLE
Upgrade to Vue3

### ISSUE THREAD

**Issue by RainnyX** [xrnl/aginun#113] opened 2020-11-08 14:15 UTC
## Problem that this feature solves
To future proof this project and to fully support typescript with the new composition api, a upgrade to Vue3 is needed.

**Comment by aleesaan** [comment] 2020-11-09 20:22
I'm afraid we will have to wait for this, as vuetify does not support vue 3 - [they expect vuetify 3 to be done next summer](https://vuetifyjs.com/en/introduction/roadmap/). Still, I would migrate to typescript already, and upgrade to vue 3 once it's more stable ([as they also are working on a migration build](https://v3.vuejs.org/guide/migration/introduction.html#breaking-changes)). What do you think?

**Comment by RainnyX** [comment] 2020-11-09 22:07
Fully agree, already busy integrating typescript ;)

**Comment by SamLubbers** [comment] 2021-06-05 13:39
Woops, I accidentally just made a duplicate of this issue #186. I'll keep the other one as it contains information about the dependencies to other issues that need to be implemented first.

**Closed by SamLubbers** 2021-06-05 13:39 UTC
Labels: suggestion
