### ISSUE TITLE
No roles are received from Hasura after logging in

### ISSUE THREAD

**Issue by tomootes** [xrnl/aginun#159] opened 2021-05-12 09:01 UTC
## Steps to reproduce the problem

1. Check out branche **feature/authorization-hasura-130**
2. Log in
3. GraphQl gives no roles back from the query

## Expected result after following these steps

Roles should be visible when the user is logged in and requests roles

**Comment by tomootes** [comment] 2021-05-12 10:12
@SamLubbers could you check this out with me? I don't have a lot of experience in Hasura neither GraphQL.

I commented out some language query lines in Hasura and now it works:
http://178.62.229.109/console/data/default/schema/public/functions/rolesSearch/modify
 
It seems that when the user is logged in, it doesn't have access to the `x-hasura-lang` header. Do you have any ideas?

**Comment by SamLubbers** [comment] 2021-05-15 13:44
@tomootes I'm looking into it :eyes:

**Comment by SamLubbers** [comment] 2021-05-15 15:01
@tomootes I still don't know what the issue is... Here is what I've found so far:


1. The `user` `x-hasura-role` does have access to the `role` table. In the note on [this section](https://hasura.io/docs/latest/graphql/core/databases/postgres/schema/custom-functions.html#permissions-for-custom-functions) of the documentation you can read about this. This is also proven by your change of removing `x-hasura-lang` from the code.

2. requests work well within Hasura

![image](https://user-images.githubusercontent.com/15846595/118365840-9ee1f200-b59e-11eb-8c09-a2d4e71b33e5.png)

3. Because requests work from within Hasura, I thought maybe the `x-hasura-lang` wasn't set from the front-end. This is not the case, as the header is sent correctly.

**Comment by SamLubbers** [comment] 2021-05-16 08:50
I looked into the Hasura logs and found the root of the problem: when logged in (with `role = user`) Hasura doesn't forward the `x-hasura-lang` header into `user-vars`. This is the HTTP log when a request is made with the language:

```json
{
  "type": "http-log",
  "timestamp": "2021-05-16T08:41:22.299+0000",
  "level": "info",
  "detail": {
    "operation": {
      "query_execution_time": 2.031711e-3,
      "user_vars": { "x-hasura-role": "user" },
      "request_id": "ec3b653c-dbfd-4a6f-a9ea-b8090287c4df",
      "r esponse_size": 88,
      "request_read_time": 5.997e-6
    },
    "request_id": "ec3b653c-dbfd-4a6f-a9 ea-b8090287c4df",
    "http_info": {
      "status": 200,
      "http_version": "HTTP/1.1",
      "url": "/v1/graphql",
      "ip": "85.148.171.175",
      "method": "POST",
      "content_encoding": "gzip"
    }
  }
}
```

I double checked with the browser that the header is indeed sent correctly. Here are the cookie logs for that same request:

```
POST /v1/graphql HTTP/1.1
Host: 178.62.229.109
User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:88.0) Gecko/20100101 Firefox/88.0
Accept: */*
Accept-Language: en-GB,en;q=0.8,nl;q=0.5,es;q=0.3
Accept-Encoding: gzip, deflate
Referer: http://localhost:8080/
content-type: application/json
x-hasura-lang: en
authorization: Bearer xxx
Origin: http://localhost:8080
Content-Length: 132
Connection: keep-alive
```

Now what I need to figure out is why Hasura doesn't forward the header and how I can fix it.

**Comment by SamLubbers** [comment] 2021-05-16 11:31
@tomootes After some hours doing research I found out that Hasura session variables (headers with the format `x-hasura-*`) are linked to the JWT authenitcation, and that because of that we were getting this issue. From the [Hasura JWT Docs](https://hasura.io/docs/latest/graphql/core/auth/authentication/jwt.html#tl-dr) I read that:

> The JWT must contain: ... other optional x-hasura-* fields

I found out about this from [this issue](https://github.com/hasura/graphql-engine/issues/3380), where someone was trying to do something very similar to us. From that issue, I ended up at [this open Hasura issue](https://github.com/hasura/graphql-engine/issues/1601), where people are requesting to allow using headers as Hasura variables. In fact, in [this comment](https://github.com/hasura/graphql-engine/issues/1601#issuecomment-786560821) you can see someone advocating for this feature so they can send the selected langauge in the header, just like we want to do.

Until that issue is resolved by the Hasura team, we'll just pass the language as a query argument. I've implemented that in [this commit](https://github.com/xrnl/aginun/commit/1830ec7f584490f8c179eeae1d2c406e4b076e8e)

**Closed by SamLubbers** 2021-05-16 11:31 UTC
Labels: bug
